// Mocks generated by Mockito 5.4.6 from annotations
// in civic/test/widgets/upvote_button_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:civic/models/complaint.dart' as _i2;
import 'package:civic/repositories/complaint_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeComplaint_0 extends _i1.SmartFake implements _i2.Complaint {
  _FakeComplaint_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ComplaintRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockComplaintRepository extends _i1.Mock
    implements _i3.ComplaintRepository {
  MockComplaintRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Complaint>> getAllComplaints({
    String? category,
    String? status,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllComplaints, [], {
              #category: category,
              #status: status,
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Complaint>>.value(
              <_i2.Complaint>[],
            ),
          )
          as _i4.Future<List<_i2.Complaint>>);

  @override
  _i4.Future<List<_i2.Complaint>> getMyComplaints() =>
      (super.noSuchMethod(
            Invocation.method(#getMyComplaints, []),
            returnValue: _i4.Future<List<_i2.Complaint>>.value(
              <_i2.Complaint>[],
            ),
          )
          as _i4.Future<List<_i2.Complaint>>);

  @override
  _i4.Future<_i2.Complaint> getComplaintById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getComplaintById, [id]),
            returnValue: _i4.Future<_i2.Complaint>.value(
              _FakeComplaint_0(
                this,
                Invocation.method(#getComplaintById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Complaint>);

  @override
  _i4.Future<_i2.Complaint> createComplaint({
    required String? category,
    required String? description,
    required double? lat,
    required double? lng,
    _i5.File? imageFile,
    String? voiceNoteUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createComplaint, [], {
              #category: category,
              #description: description,
              #lat: lat,
              #lng: lng,
              #imageFile: imageFile,
              #voiceNoteUrl: voiceNoteUrl,
            }),
            returnValue: _i4.Future<_i2.Complaint>.value(
              _FakeComplaint_0(
                this,
                Invocation.method(#createComplaint, [], {
                  #category: category,
                  #description: description,
                  #lat: lat,
                  #lng: lng,
                  #imageFile: imageFile,
                  #voiceNoteUrl: voiceNoteUrl,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Complaint>);

  @override
  _i4.Future<({bool hasUpvoted, int upvotes})> toggleUpvote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleUpvote, [id]),
            returnValue: _i4.Future<({bool hasUpvoted, int upvotes})>.value((
              hasUpvoted: false,
              upvotes: 0,
            )),
          )
          as _i4.Future<({bool hasUpvoted, int upvotes})>);

  @override
  _i4.Future<String> uploadVoiceNote(_i5.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#uploadVoiceNote, [file]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#uploadVoiceNote, [file]),
              ),
            ),
          )
          as _i4.Future<String>);
}
